"""separate_org_and_dept_memberships

Revision ID: 246d278f0e71
Revises: 1a478ef10f05
Create Date: 2026-05-05 13:22:29.212818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '246d278f0e71'
down_revision: Union[str, Sequence[str], None] = '1a478ef10f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dept_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'MEMBER', 'VIEWER', name='deptrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department_id', name='uq_user_dept')
    )
    op.alter_column('org_memberships', 'role',
               existing_type=postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='userrole'),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='orgrole'),
               existing_nullable=False)
    op.drop_constraint(op.f('org_memberships_department_id_fkey'), 'org_memberships', type_='foreignkey')
    op.drop_column('org_memberships', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_memberships', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('org_memberships_department_id_fkey'), 'org_memberships', 'departments', ['department_id'], ['id'])
    op.alter_column('org_memberships', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='orgrole'),
               type_=postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='userrole'),
               existing_nullable=False)
    op.drop_table('dept_memberships')
    # ### end Alembic commands ###
